{"seeAlsoSections":[{"title":"Errors","identifiers":["doc:\/\/NordicWiFiProvisioner\/documentation\/NordicWiFiProvisioner\/ConnectionFailureReason","doc:\/\/NordicWiFiProvisioner\/documentation\/NordicWiFiProvisioner\/ProvisionerError","doc:\/\/NordicWiFiProvisioner\/documentation\/NordicWiFiProvisioner\/ProvisionerInfoError"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceNotConnectedError"}],"title":"DeviceNotConnectedError","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"s:21NordicWiFiProvisioner23DeviceNotConnectedErrorV","modules":[{"name":"NordicWiFiProvisioner"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceNotConnectedError"}]},"abstract":[{"type":"text","text":"Error that is thrown when the request to the device was sent, but the device is not connected"}],"sections":[],"identifier":{"url":"doc:\/\/NordicWiFiProvisioner\/documentation\/NordicWiFiProvisioner\/DeviceNotConnectedError","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/NordicWiFiProvisioner\/s5ErrorP","doc:\/\/NordicWiFiProvisioner\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/NordicWiFiProvisioner\/documentation\/NordicWiFiProvisioner"]]},"topicSections":[{"title":"Default Implementations","identifiers":["doc:\/\/NordicWiFiProvisioner\/documentation\/NordicWiFiProvisioner\/DeviceNotConnectedError\/Error-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/nordicwifiprovisioner\/devicenotconnectederror"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceNotConnectedError"}],"languages":["swift"],"platforms":["macOS"]}]}],"references":{"doc://NordicWiFiProvisioner/documentation/NordicWiFiProvisioner/ProvisionerError":{"role":"symbol","title":"ProvisionerError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProvisionerError"}],"abstract":[],"identifier":"doc:\/\/NordicWiFiProvisioner\/documentation\/NordicWiFiProvisioner\/ProvisionerError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProvisionerError"}],"url":"\/documentation\/nordicwifiprovisioner\/provisionererror"},"doc://NordicWiFiProvisioner/documentation/NordicWiFiProvisioner/DeviceNotConnectedError/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/NordicWiFiProvisioner\/documentation\/NordicWiFiProvisioner\/DeviceNotConnectedError\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/nordicwifiprovisioner\/devicenotconnectederror\/error-implementations"},"doc://NordicWiFiProvisioner/documentation/NordicWiFiProvisioner/ConnectionFailureReason":{"role":"symbol","title":"ConnectionFailureReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionFailureReason"}],"abstract":[{"type":"text","text":"Error that can occur during connection to the network."}],"identifier":"doc:\/\/NordicWiFiProvisioner\/documentation\/NordicWiFiProvisioner\/ConnectionFailureReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConnectionFailureReason"}],"url":"\/documentation\/nordicwifiprovisioner\/connectionfailurereason"},"doc://NordicWiFiProvisioner/documentation/NordicWiFiProvisioner/ProvisionerInfoError":{"role":"symbol","title":"ProvisionerInfoError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProvisionerInfoError"}],"abstract":[],"identifier":"doc:\/\/NordicWiFiProvisioner\/documentation\/NordicWiFiProvisioner\/ProvisionerInfoError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProvisionerInfoError"}],"url":"\/documentation\/nordicwifiprovisioner\/provisionerinfoerror"},"doc://NordicWiFiProvisioner/documentation/NordicWiFiProvisioner":{"role":"collection","title":"NordicWiFiProvisioner","abstract":[{"type":"codeVoice","code":"NordicWiFiProvisioner"},{"type":"text","text":" allows you to provision an nRF-7 Series device with a WiFi network, read the device information, and scan for nearby WiFi networks."}],"identifier":"doc:\/\/NordicWiFiProvisioner\/documentation\/NordicWiFiProvisioner","kind":"symbol","type":"topic","url":"\/documentation\/nordicwifiprovisioner"},"doc://NordicWiFiProvisioner/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/NordicWiFiProvisioner\/s8SendableP"},"doc://NordicWiFiProvisioner/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/NordicWiFiProvisioner\/s5ErrorP"},"doc://NordicWiFiProvisioner/documentation/NordicWiFiProvisioner/DeviceNotConnectedError":{"role":"symbol","title":"DeviceNotConnectedError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceNotConnectedError"}],"abstract":[{"type":"text","text":"Error that is thrown when the request to the device was sent, but the device is not connected"}],"identifier":"doc:\/\/NordicWiFiProvisioner\/documentation\/NordicWiFiProvisioner\/DeviceNotConnectedError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeviceNotConnectedError"}],"url":"\/documentation\/nordicwifiprovisioner\/devicenotconnectederror"}}}